# Le pipeline se déclenche lors d'une modification sur la branche master
trigger:
- master

stages:
# 1. Exécuter les tests unitaires
- stage: BuildAndTest
  pool:
    name: "windows self-hosted"
  jobs:
  - job: BuildAndRunUnitTests
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/XUnitTestProject.csproj'
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\XUnitTestProject.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        failOnMinTestsNotRun: false

# 2. Construire et pousser une nouvelle image vers un repo Docker Hub
- stage: Docker
  dependsOn: BuildAndTest
  pool:
    name: "docker self-hosted"
  jobs:
    - job: BuildAndPushImage
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker hub pierreeymeryciao'
            repository: 'pierreeymeryciao/my-web-app-with-tests'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            addPipelineData: false

# 3. Déployer la nouvelle image dans notre App Service Azure
- stage: DeployImage
  dependsOn: Docker
  pool:
    name: "docker self-hosted"
  jobs:
    - job: Deploy
      steps:
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Abonnement Visual Studio Professional (3f012e51-17da-47ae-b679-97c3367e9fc6)'
          appType: 'webAppContainer'
          WebAppName: 'mywebappwithtests'
          DockerNamespace: 'pierreeymeryciao'
          DockerRepository: 'my-web-app-with-tests'
          DockerImageTag: '$(Build.BuildId)'

