# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: BuildAndTest
  pool:
    name: 'docker self-hosted'
  jobs:
  - job: BuildAndRunUnitTests
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/XUnitTestProject.csproj'
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\XUnitTestProject.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        vsTestVersion: '16.0'
        failOnMinTestsNotRun: false

- stage: Docker
  dependsOn: BuildAndTest
  pool:
    vmImage: "ubuntu-16.04"
  jobs:
    - job: BuildAndPushImage
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker hub pierreeymeryciao'
            repository: 'pierreeymeryciao/my-web-app-with-tests'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            addPipelineData: false

- stage: DeployImage
  dependsOn: Docker
  jobs:
    - job: Deploy
      steps:
      - task: AzureWebAppContainer@1
        inputs:
          azureSubscription: 'Abonnement Visual Studio Professional (3f012e51-17da-47ae-b679-97c3367e9fc6)'
          appName: 'mywebappwithtests'
          containers: 'pierreeymeryciao/my-web-app-with-tests'
