# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    windows:
      imageName: "vs2017-win2016"
  maxParallel: 2

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\XUnitTestProject.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    vsTestVersion: '16.0'
    failOnMinTestsNotRun: false
- task: Docker@2
  inputs:
    containerRegistry: 'docker hub pierreeymeryciao'
    repository: 'pierreeymeryciao/my-web-app-with-tests'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
